random.seed=42
repetition.number=1
confidence.level=0.95

# Possible values for experiment are;
# base
experiment=base

# Arrival params
distribution.arrivals.mu=0.15
distribution.arrivals.cv=4

# Services params
distribution.services.z=0.16
distribution.services.cv=4

# Distribution type
distribution.arrivals.type=h2
distribution.services.type=h2

# Stop condition value
system.empty_jobs=false
system.stop=10000

# Server capacities
webserver.capacity=1
spikeserver.capacity=1

# Infrastructure params
infrastructure.start_num_server=1
infrastructure.max_num_server=1
infrastructure.scheduler=leastUsed
infrastructure.si_max=90
infrastructure.spikeserver.active=true

# Long-term fluctuations
distribution.arrivals.total_period=0
distribution.arrivals.fast_interval=0
distribution.arrivals.fast_mu=0