random.seed=42
repetition.number=1
confidence.level=0.95

# Possible values for experiment are;
# base | ver-base | val-base-1 | val-base-2
# base-exp-1
experiment=val-base-2

# Arrival params
distribution.arrivals.mu=0.15
distribution.arrivals.cv=4

# Services params
distribution.services.z=0.16
distribution.services.cv=4

# Distribution type
distribution.arrivals.type=h2
distribution.services.type=h2

# Stop condition value
system.empty_jobs=true
system.stop=50000

# Server capacities
webserver.capacity=1
spikeserver.capacity=1

# Infrastructure params
infrastructure.start_num_server=1
infrastructure.max_num_server=1
infrastructure.scheduler=leastUsed
infrastructure.si_max=90
infrastructure.spikeserver.active=true

# Long-term fluctuations
distribution.arrivals.total_period=0
distribution.arrivals.fast_interval=0
distribution.arrivals.fast_mu=0

output.dir=output

batch.size=16384

log.fine=true

turn.on.mu=5
turn.on.std=0.5

# r0 | jobs
scaling.indicator.type=r0
scaling.out.threshold=2
sliding.window.size=5